spring.application.name=Just Another Movie Site

spring.datasource.url=jdbc:mariadb://localhost:3306/jams
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.thymeleaf.cache=false